resilience4j.circuitbreaker.instances.fallback.register-health-indicator=true
resilience4j.circuitbreaker.instances.fallback.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.fallback.sliding-window-size=2
resilience4j.circuitbreaker.instances.fallback.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.fallback.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fallback.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.fallback.record-exceptions=java.lang.RuntimeException
logging.level.root=INFO
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
